"""user details

Revision ID: 967ab68e5583
Revises: 
Create Date: 2026-09-10 11:13:05.644488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967ab68e5583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expense_Tracker', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('Expense_Tracker', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('Monthly_Budget', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('Monthly_Budget', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Monthly_Budget', 'user_name')
    op.drop_column('Monthly_Budget', 'user_id')
    op.drop_column('Expense_Tracker', 'user_name')
    op.drop_column('Expense_Tracker', 'user_id')
    # ### end Alembic commands ###
